"""added client data to widget data corrected error 2

Revision ID: c749ddfb5618
Revises: 1fc4ef13ac3f
Create Date: 2023-04-10 19:13:00.350666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c749ddfb5618'
down_revision = '1fc4ef13ac3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_constraint('client_widget_data_id_fkey', type_='foreignkey')
        batch_op.drop_column('widget_data_id')

    with op.batch_alter_table('widget_data', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['client_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('widget_data', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('widget_data_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('client_widget_data_id_fkey', 'widget_data', ['widget_data_id'], ['id'])

    # ### end Alembic commands ###
